name: Deploy to Render

on:
  push:
    branches:
      - main # or "master" if you use that

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
